cthulhu:
  chart: ts-deployment/cthulhu
  replicaCount: 1
  appName: "imago"
  imagePullPolicy: IfNotPresent
  containerHost: "docker-repo.hero3d.net"
  imageBasePath: "docker-repo.hero3d.net/deployments/"
  appPort: "3000"
  configPalEnvironment: "dev"
  configPalTlc:  "imago"
  configPalServers:  "zookeeper.hero3d.net:2181"
  configPalOrgServers:  "zookeeper.hero3d.net:2181"
  useWorkerNodes: false
  includeResqueWeb: false
  includePrometheusExporter: false
  includeIngress: true
  ingressClass: "ingress-internal-ts"
  appDomain: "dev.hero3d.net"
  envars:
    - name: MARTINI_ENV
      value: "development"
  resources:
      requests:
          memory: 10Mi
          cpu: 100m
      limits:
          memory: 20Mi
          cpu: 1