name: restart
on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        decription: Deployment environment
        options:
          - dev
          - qa
          - prod
jobs:
  slack-approval-request:
    if: github.event.inputs.environment == 'prod'
    runs-on: [ default, amd64 ]
    steps:
      - name: Post slack approval request
        uses: turbosquid/actions/slack-request-approval@v3
        with:
          slack_token: ${{ secrets.SLACK_BOT_APP_TOKEN }}
          channel: "ts-cthulhu"
          header: "Production restart requested"
          details: |
            Github user _${{github.actor}}_ would like to RESTART the current deployment for *${GITHUB_REPOSITORY}* in production.
  roll:
    runs-on: [ default, amd64 ]
    environment:
      name:  ${{ github.event.inputs.environment }}
    env:
      ENV:  ${{ github.event.inputs.environment }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: restart
        id: restart
        uses: turbosquid/actions/argocd-rollout-restart@v3
        with:
          argocd_token: ${{ secrets.ARGOCD_TOKEN }}
          cluster: turbosquid-a
          environment: ${{ env.ENV }}
          slack_token: ${{ secrets.SLACK_BOT_APP_TOKEN }}
