name: update-deployment
on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Deployment environment
        options:
          - dev
          - qa
          - prod
jobs:
  slack-approval-request:
    if: github.event.inputs.environment == 'prod'
    runs-on: [ default, amd64 ]
    steps:
      - name: Post slack approval request
        uses: turbosquid/actions/slack-request-approval@v3
        with:
          slack_token: ${{ secrets.SLACK_BOT_APP_TOKEN }}
          channel: "ts-cthulhu"
          header: "Production REDEPLOY requested"
          details: |
            Github user _${{github.actor}}_ would like to REDEPLOY the current deployment for *${GITHUB_REPOSITORY}* in production.
  redeploy:
    environment:
      name:  ${{ github.event.inputs.environment }}
    env:
      ENV: ${{ github.event.inputs.environment }}
    runs-on: [ default, amd64 ]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - id: get_image
        uses: turbosquid/actions/get-helm-set-value@v3
        with:
          argocd_token: ${{ secrets.ARGOCD_TOKEN }}
          cluster: turbosquid-a
          environment: ${{ github.event.inputs.environment }}
          parameter: "appImage"
      - name: Redeploy via ArgoCD
        id: deploy
        uses: turbosquid/actions/argocd-deploy@v3
        with:
          argocd_token: ${{ secrets.ARGOCD_TOKEN }}
          slack_token: ${{ secrets.SLACK_BOT_APP_TOKEN }}
          slack_channel: ts-cthulhu
          cluster: turbosquid-a
          environment: ${{ github.event.inputs.environment }}
          image_name: "${{ steps.get_image.outputs.value  }}"
          helm_chart_path: helm-charts/app
          values_files: "values-${{ env.ENV }}.yaml"
          helm_set: "cthulhu.migrateCommand=" # Null out migrate command so we do not try to migrate
          is_ephemeral: "false"
